; PROGRAM TO RECEIVE DATA FROM THE SERIAL PORT
ORG 0000H
MOV TMOD, #20H
MOV TH1, #0FAH
MOV SCON, #50H
SETB TR1

HERE: JNB RI, HERE

MOV A,SBUF
MOV P1,A
CLR RI
SJMP HERE

; DATA CAN BE SENT BY TYPING INTO THE UART WINDOW.. IT WONT SHOW BUT WILL REFLECT ON P1