; Code to perform addition and provide output in BCD format

ORG 0000H
MOV R2,#4H; INTIALIZE COUNT TO ADD 4 TIMES
MOV R0,#40H ; INITALIZE DESTINATION POINTER
MOV DPTR,#120H ; INITALIZE SOURCE POINTER

LOOP:CLR A
MOVC A,@A+DPTR ; FETCH A BYTE FROM THE MULTIBYTE DATA
MOV R1,A
MOV A,#30H;
MOVC A,@A+DPTR; FETCH A BYTE FROM THE MULTIBYTE DATA
ADDC A,R1; ADD WITH CARRY
DA A; DECIMAL ADJUST ACCUMULATOR
MOV @R0,A; MOVE THE RESULT TO RAM
INC R0
INC DPTR
DJNZ R2,LOOP; CHECK FOR COUNT

HERE: SJMP HERE

ORG 120H
DB 54H,76H,65H,98H
ORG 150H
DB 93H,56H,77H,38H
END