; Code to transfer data from Code space to Data Space

ORG 0000H;
MOV A, #00H;
MOV DPTR, #0200H; SET THE DATA POINTER TO POINT TO THE ADDRESS 200H
MOV R7,#0AH; LOAD THE SIZE OF THE STRING TO BE COPIED
MOV R0,#45H; LOAD THE STARTING ADDRESS TO WHERE THE STRING SHOULD BE COPIED TO IN RAM/DATA SPACE

LOOP:   CLR A;
        MOVC A, @A+DPTR; MOVE THE DATA POINTED TO, TO THE ACCUMULATOR
        MOV @R0,A; MOVE THE COPIED DATA TO LOCAITON POINTED BY R0. @ IS DE-REFERENCE (In CPP Terms)
        INC DPTR; POINT TO THE NEXT MEM LOCATION, CHARACTER
        INC R0; INCREMENT RO, SIMILAR TO INCREMENTING INDEX..
        DJNZ R7,LOOP; DECREMENT, JUMP IF NOT ZERO TO LOOP
		
HERE:   SJMP HERE;
        ORG 0200H;
        DB "DEEP JIWAN";
        END