; Code for interrupts usage

ORG 0000H
LJMP INIT

ORG 000BH
; TIMER 0 ISR
CPL P0.1 ; SQUARE WAVE
RETI

ORG 0023H
; SERIAL ISR
LJMP SERIAL ; SEND DATA TO P0

INIT:
MOV IE, #92H; ENABLE INTERUPTS
MOV P0, #00H ; P0 AS OUTPUT (SQUARE WAVE)
MOV P1, #0FFH ; P1 AS INPUT

MOV TMOD, #22H
MOV TH0, #0E8H; LOAD TIMER0
MOV TL0, #0E8H;

MOV TH1, #0FAH ; 4800 BAUD
MOV SCON, #50H

SETB TR1 ; FOR SERIAL TRANSMIT
SETB TR0 ; START T0

MAIN:
READ_AND_SEND:
; P1 PORT READ
MOV A,P1;
MOV P2,A ; P2 GETS A COPY
MOV SBUF,A; TRANSMIT SERIALLY
HERE: JNB TI, HERE
SJMP MAIN


ORG 0100H
SERIAL:
; SERIAL ISR
JB TI, TRANSMIT ; CHECK IF ITS A TRANSMIT INTERUPT
MOV A,SBUF ; RECEIVE,   IF ITS A RECEIVCE INTERUPT
MOV P0,A ; SEND TO P0
CLR RI;
RETI

TRANSMIT: 
CLR TI
RETI

END